version: '3'

services:
  server:
    image: ghcr.io/drakeapps/cloud-led-controller/server-rpi
    build:
      context: .
    devices:
      - /dev/snd:/dev/snd
    privileged: true
    env_file: .env
    ports:
      - 6789:6789
  ssl:
    image: ghcr.io/drakeapps/cloud-led-controller/server-ssl-rpi
    build:
      context: ssl/
    ports:
      - 443:443
    volumes:
      - /var/opt/ssl/:/etc/nginx/ssl/
  webui:
    image: ghcr.io/drakeapps/cloud-led-controller/webui
    build:
      context: web-ui/
    ports:
      - 80:80
