version: '3'

services:
  server:
    image: ghcr.io/drakeapps/cloud-led-controller/server-rpi
    restart: unless-stopped
    build:
      context: .
    devices:
      - /dev/snd:/dev/snd
    privileged: true
    env_file: .env
    ports:
      - 6789:6789
  ssl:
    image: ghcr.io/drakeapps/cloud-led-controller/server-ssl
    restart: unless-stopped
    build:
      context: ssl/
    ports:
      - 443:443
    volumes:
      - /var/opt/ssl/:/etc/nginx/ssl/
  webui:
    image: ghcr.io/drakeapps/cloud-led-controller/webui
    restart: unless-stopped
    build:
      context: web-ui/
    ports:
      - 80:80
  mqtt-sound:
    image: ghcr.io/drakeapps/cloud-led-controller/mqqt
    restart: unless-stopped
    build:
      context: mqtt-websocket-proxy/
    command: "node sound.js --mqttHost $${MQTTHOST} --wsURL $${WSURL}"
  mqtt-color:
    image: ghcr.io/drakeapps/cloud-led-controller/mqtt
    restart: unless-stopped
    build:
      context: mqtt-websocket-proxy/
    command: "node color.js --mqttHost $${MQTTHOST} --wsURL $${WSURL}"
