version: '3'

services:
  server:
    image: ghcr.io/drakeapps/cloud-led-controller/server-rpi
    build:
      context: .
    devices:
      - /dev/snd:/dev/snd
    privileged: true
    env_file: .env
    ports:
      - 6789:6789
  webui:
    image: ghcr.io/drakeapps/cloud-led-controller/webui
    build:
      context: web-ui/
    ports:
      - 80:80
